### PR TITLE
fix regex for better determine `ttynumber`

### PR DESCRIPTION
**Pull request by boozook**

### CODE REVIEW

**Comment by inket** [comment]
It doesn't seem to be working here.

screen shot 2016-12-31 at 1 53 00 a

**Comment by boozook** [comment]
fixed:
screen shot 2017-01-01 at 18 41 32

screen shot 2017-01-01 at 18 42 28

This one term inited with old ttynumber => so you see `()` empty number:
screen shot 2017-01-01 at 18 39 19

**Comment by inket** [comment]
Thank you!

**Comment by boozook** [comment]
I think `*?` non greedy quantifier there will be better but I wasn't able to win the strange sed's regex :(
So we need matching group. Maybe we should use perl (perl is required by POSIX) but it's one more dependency.

It because what if `tty` return value with 4 or more digits?.. Is it really impossible?

**Comment by inket** [comment]
Hehe. For lots of things bash-related, I learned that as long as it works, don't waste your time trying to improve it :D

**Comment by boozook** [comment]
Okay :)

**Pull request merged**
